[tool.poetry]
name = "sbobot"
version = "0.0.1"
description = ""
authors = ["Andrew Clemons <andrew.clemons@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.11.9"

aiohttp = "3.9.5"
boto3 = "1.34.120"
fastapi-slim = "0.111.0"
orjson = "3.10.3"
python-gitlab = "4.6.0"
structlog = "24.2.0"
uvicorn = {version = "0.30.1", extras = ["standard"]}
yarl = "1.9.4"

[tool.poetry.group.dev.dependencies]
boto3-stubs = { version = "1.34.120", extras = ["ssm"] }
pyright = "1.1.366"
pytest = "8.2.2"
ruff = "0.4.8"
ruff-lsp = "0.0.53"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.select = ["ALL"]
lint.ignore = [
 "D", # disable docstring checks
 "E501", # black handles long line wrapping
 "COM812", # conflicts with ruff format
 "ISC001", # conflicts with ruff format
]
target-version = "py39"

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Body", "fastapi.Depends", "fastapi.Security"]

[tool.ruff.lint.mccabe]
max-complexity = 12
