[tool.poetry]
name = "sbo-bot-gitlab-webhook"
version = "0.0.1"
description = ""
authors = ["Andrew Clemons <andrew.clemons@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.9.18"

fastapi = "0.109.0"
orjson = "3.9.12"
uvicorn = {version = "0.27.0", extras = ["standard"]}
yarl = "1.9.4"
boto3 = "^1.34.34"

[tool.poetry.group.dev.dependencies]
boto3-stubs = { version = "1.34.27", extras = ["ssm"] }
pyright = "1.1.348"
pytest = "8.0.0"
ruff = "0.1.14"
ruff-lsp = "0.0.50"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["ALL"]
ignore = [
 "D", # disable docstring checks
 "E501", # black handles long line wrapping
 "COM812", # conflicts with ruff format
 "ISC001", # conflicts with ruff format
]
target-version = "py39"
