[tool.poetry]
name = "sbobot"
version = "0.0.1"
description = ""
authors = ["Andrew Clemons <andrew.clemons@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.9.18"

aiohttp = "3.9.3"
boto3 = "1.34.49"
fastapi = "0.109.2"
orjson = "3.9.14"
python-gitlab = "4.4.0"
structlog = "24.1.0"
uvicorn = {version = "0.27.1", extras = ["standard"]}
yarl = "1.9.4"

[tool.poetry.group.dev.dependencies]
boto3-stubs = { version = "1.34.49", extras = ["ssm"] }
pyright = "1.1.350"
pytest = "8.0.0"
ruff = "0.2.2"
ruff-lsp = "0.0.52"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.select = ["ALL"]
lint.ignore = [
 "D", # disable docstring checks
 "E501", # black handles long line wrapping
 "COM812", # conflicts with ruff format
 "ISC001", # conflicts with ruff format
]
target-version = "py39"

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Body", "fastapi.Depends", "fastapi.Security"]
